spring:
  http:
    multipart:
      max-file-size: 1800mb
      max-request-size: 1800mb
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pan
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  messages:
    encoding: UTF-8
server:
  port: 18080
  tomcat:
    uri-encoding: utf-8
#文件存储路径
prop:
  upload-folder: files/

#设置最大上传大小为10Mb


